// <auto-generated />
using System;
using AluguelMotos.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AluguelMotos.Repository.Migrations
{
    [DbContext(typeof(AluguelMotosContext))]
    partial class AluguelMotosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("AluguelMotos.Infraestructure.Interfaces.Repositories.Entregador", b =>
                {
                    b.Property<Guid>("EntregadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemCNH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeloCNH")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntregadorId");

                    b.ToTable("Entregadores");
                });

            modelBuilder.Entity("AluguelMotos.Infraestructure.Interfaces.Repositories.Moto", b =>
                {
                    b.Property<Guid>("MotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeletedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Renavan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MotoId");

                    b.ToTable("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
